include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@release-service-sandbox # <-- instead of @master
  # - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

stages:
  - "build"
  - "release"

variables:
  TARBALL_ARTIFACT_PATH: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

build-release-tarball:
  stage: "build"
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make dist
    - gunzip <"${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz" | xz > "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"
    - rm -f "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz" "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.bz2"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: "always"
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
